include ../../plugin_defs

OBJS = $(OBJDIR)/timestretch.o \
	$(OBJDIR)/timestretchengine.o

PLUGIN = timestretch

include ../../plugin_config




$(OBJDIR)/timestretch.o: timestretch.C
$(OBJDIR)/timestretchengine.o: timestretchengine.C

