include ../../plugin_defs

OBJS = $(OBJDIR)/brightness.o  \
	$(OBJDIR)/brightnesswindow.o

PLUGIN = brightness

include ../../plugin_config


$(OBJDIR)/brightness.o: brightness.C
$(OBJDIR)/brightnesswindow.o: brightnesswindow.C
