include ../../plugin_defs

OBJS = $(OBJDIR)/blurzoom.o  \
	$(OBJDIR)/blurzoomwindow.o

PLUGIN = blurzoom

include ../../plugin_config

$(OBJDIR)/blurzoom.o: blurzoom.C
$(OBJDIR)/blurzoomwindow.o: blurzoomwindow.C
