include ../../plugin_defs

OBJS = 	$(OBJDIR)/translate.o  \
	$(OBJDIR)/translatewin.o

PLUGIN = translate

include ../../plugin_config

$(OBJDIR)/translate.o: translate.C
$(OBJDIR)/translatewin.o: translatewin.C
