include ../../plugin_defs

OBJS = \
	$(OBJDIR)/bistogram.o \
	$(OBJDIR)/bistogramconfig.o \
	$(OBJDIR)/bistogramwindow.o

PLUGIN = histogram_bezier

include ../../plugin_config

$(OBJDIR)/bistogram.o: bistogram.C
$(OBJDIR)/bistogramconfig.o: bistogramconfig.C
$(OBJDIR)/bistogramwindow.o: bistogramwindow.C
