include ../../plugin_defs

OBJS := \
	$(OBJDIR)/histogramengine.o \
	$(OBJDIR)/threshold.o \
	$(OBJDIR)/thresholdwindow.o

PLUGIN = threshold


include ../../plugin_config



$(OBJDIR)/threshold.o:        threshold.C
$(OBJDIR)/thresholdwindow.o:  thresholdwindow.C
$(OBJDIR)/histogramengine.o:  histogramengine.C




