include ../../plugin_defs

OBJS := \
	$(OBJDIR)/unsharp.o \
	$(OBJDIR)/unsharpwindow.o

PLUGIN = unsharp

include ../../plugin_config

$(OBJDIR)/unsharp.o: unsharp.C
$(OBJDIR)/unsharpwindow.o: unsharpwindow.C
