include ../../plugin_defs

OBJS = $(OBJDIR)/deinterlace.o  \
	$(OBJDIR)/deinterwindow.o

PLUGIN = deinterlace

include ../../plugin_config

$(OBJDIR)/deinterlace.o: deinterlace.C
$(OBJDIR)/deinterwindow.o: deinterwindow.C



