include ../../plugin_defs

OBJS := \
	$(OBJDIR)/motion-hv.o \
	$(OBJDIR)/motioncache-hv.o \
	$(OBJDIR)/motionscan-hv.o \
	$(OBJDIR)/motionwindow-hv.o

PLUGIN = motion-hv

include ../../plugin_config

$(OBJDIR)/motion-hv.o: motion-hv.C
$(OBJDIR)/motioncache-hv.o: motioncache-hv.C
$(OBJDIR)/motionscan-hv.o: motionscan-hv.C
$(OBJDIR)/motionwindow-hv.o: motionwindow-hv.C
