include ../../plugin_defs

OBJS := \
	$(OBJDIR)/motion.o \
	$(OBJDIR)/motionscan.o \
	$(OBJDIR)/motionwindow.o

PLUGIN = motion

include ../../plugin_config

$(OBJDIR)/motion.o: motion.C
$(OBJDIR)/motionscan.o: motionscan.C
$(OBJDIR)/motionwindow.o: motionwindow.C
