include ../../plugin_defs

OBJS = $(OBJDIR)/greycstorationwindow.o $(OBJDIR)/greycstorationplugin.o
PLUGIN = greycstoration

include ../../plugin_config

$(OBJDIR)/greycstorationwindow.o:	greycstorationwindow.C
$(OBJDIR)/greycstorationplugin.o:	greycstorationplugin.C

