include ../../plugin_defs

OBJS = $(OBJDIR)/normalize.o  \
	$(OBJDIR)/normalizewindow.o

PLUGIN = normalize

include ../../plugin_config


$(OBJDIR)/normalize.o: normalize.C
$(OBJDIR)/normalizewindow.o: normalizewindow.C
