include ../../plugin_defs

OBJS := \
	$(OBJDIR)/motion-cv.o \
	$(OBJDIR)/motionwindow-cv.o

PLUGIN = motion-cv

include ../../plugin_config

$(OBJDIR)/motion-cv.o: motion-cv.C
$(OBJDIR)/motionwindow-cv.o: motionwindow-cv.C

