include ../../plugin_defs

OBJS = \
	$(OBJDIR)/downsample.o \
	$(OBJDIR)/downsampleengine.o

PLUGIN = downsample

include ../../plugin_config

$(OBJDIR)/downsample.o: downsample.C
$(OBJDIR)/downsampleengine.o: downsampleengine.C



