include ../../plugin_defs

OBJS := \
	$(OBJDIR)/crikey.o \
	$(OBJDIR)/crikeywindow.o

PLUGIN = crikey

include ../../plugin_config

$(OBJDIR)/crikey.o: crikey.C
$(OBJDIR)/crikeywindow.o: crikeywindow.C

