include ../../plugin_defs

OBJS = $(OBJDIR)/cdripper.o \
	$(OBJDIR)/cdripwindow.o

PLUGIN = cdripper

include ../../plugin_config

$(OBJDIR)/cdripper.o: cdripper.C
$(OBJDIR)/cdripwindow.o: cdripwindow.C
