include ../../plugin_defs

OBJS = \
	$(OBJDIR)/histogram.o \
	$(OBJDIR)/histogramconfig.o \
	$(OBJDIR)/histogramwindow.o

PLUGIN = histogram

include ../../plugin_config

$(OBJDIR)/histogram.o: histogram.C
$(OBJDIR)/histogramconfig.o: histogramconfig.C
$(OBJDIR)/histogramwindow.o: histogramwindow.C
