include ../../plugin_defs

OBJS = $(OBJDIR)/deinterlace-cv.o  \
	$(OBJDIR)/deinterwindow-cv.o

PLUGIN = deinterlace-cv

include ../../plugin_config

$(OBJDIR)/deinterlace-cv.o: deinterlace-cv.C
$(OBJDIR)/deinterwindow-cv.o: deinterwindow-cv.C



