include ../../plugin_defs

OBJS = $(OBJDIR)/sharpen.o  \
	$(OBJDIR)/sharpenwindow.o

PLUGIN = sharpen

include ../../plugin_config

$(OBJDIR)/sharpen.o: sharpen.C
$(OBJDIR)/sharpenwindow.o: sharpenwindow.C
