include ../../plugin_defs

OBJS = 	$(OBJDIR)/scaleratio.o  \
	$(OBJDIR)/scaleratiowin.o

PLUGIN = scaleratio

include ../../plugin_config

$(OBJDIR)/scaleratio.o: scaleratio.C
$(OBJDIR)/scaleratiowin.o: scaleratiowin.C
