
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef APPEARANCEPREFS_INC
#define APPEARANCEPREFS_INC

class AppearancePrefs;
class TimeFormatHMS;
class TimeFormatHMSF;
class TimeFormatSamples;
class TimeFormatFrames;
class TimeFormatHex;
class TimeFormatFeet;
class TimeFormatSeconds;
class TimeFormatFeetSetting;
class ViewTheme;
class ViewThemeItem;
class ViewPluginIcons;
class ViewPluginIconItem;
class ViewThumbnails;
class UseTipWindow;
class UseWarnIndecies;
class UseWarnVersion;
class BD_WarnRoot;
class PopupMenuBtnup;
class GrabFocusPolicy;
class ActivateFocusPolicy;
class DeactivateFocusPolicy;
class ForwardRenderDisplacement;
class HighlightInverseColor;
class YuvColorSpace;
class YuvColorSpaceItem;
class YuvColorRange;
class YuvColorRangeItem;
class PrefsAutostartLV2UI;
class PerpetualSession;

#endif
