
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef ASSETPOPUP_INC
#define ASSETPOPUP_INC

#define SNAPSHOT_PNG  0
#define SNAPSHOT_JPEG 1
#define SNAPSHOT_TIFF 2
#define SNAPSHOT_PPM  3

#define GRABSHOT_PNG  0
#define GRABSHOT_JPEG 1
#define GRABSHOT_TIFF 2
#define GRABSHOT_PPM  3

class AssetPopup;
class AssetPopupInfo;
class AssetPopupSort;
class AssetPopupBuildIndex;
class AssetPopupView;
class AssetPopupViewWindow;
class AssetPopupMixer;
class AssetPopupPaste;
class AssetMatchSize;
class AssetMatchRate;
class AssetMatchAll;
class AssetPopupProjectRemove;
class AssetPopupDiskRemove;
class AssetListMenu;
class AssetPopupLoadFile;
class AssetListCopy;
class AssetCopyDialog;
class AssetCopyWindow;
class AssetListPaste;
class AssetPasteDialog;
class AssetPasteWindow;
class AssetSnapshot;
class SnapshotSubMenu;
class SnapshotMenuItem;
class AssetGrabshot;
class GrabshotSubMenu;
class GrabshotMenuItem;
class GrabshotThread;
class GrabshotPopup;

#endif
