
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef __BDCREATE_INC__
#define __BDCREATE_INC__

class CreateBD_MenuItem;
class CreateBD_Thread;
class CreateBD_OK;
class CreateBD_Cancel;
class CreateBD_DiskSpace;
class CreateBD_TmpPath;
class CreateBD_AssetTitle;
class CreateBD_Deinterlace;
class CreateBD_InverseTelecine;
class CreateBD_Scale;
class CreateBD_ResizeTracks;
class CreateBD_Histogram;
class CreateBD_LabelChapters;
class CreateBD_WideAudio;
class CreateBD_WideAspect;
class CreateBD_GUI;
class CreateBD_FormatItem;
class CreateBD_Format;
class CreateBD_MediaSize;

#endif
