
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef NEWFOLDER_INC
#define NEWFOLDER_INC

class BinFolderFilters;
class BinFolder;
class BinFolders;
class BinFolderFilter;
class BinFolderEnabled;
class BinFolderEnabledType;
class BinFolderEnabledPopup;
class BinFolderTarget;
class BinFolderTargetPatterns;
class BinFolderTargetFileSize;
class BinFolderTargetTime;
class BinFolderTargetTrackType;
class BinFolderTargetWidth;
class BinFolderTargetHeight;
class BinFolderTargetFramerate;
class BinFolderTargetSamplerate;
class BinFolderTargetChannels;
class BinFolderTargetDuration;
class BinFolderTargetType;
class BinFolderTargetPopup;
class BinFolderOp;
class BinFolderOpType;
class BinFolderOpPopup;
class BinFolderOpEQ;
class BinFolderOpGT;
class BinFolderOpGE;
class BinFolderOpNE;
class BinFolderOpLT;
class BinFolderOpLE;
class BinFolderOpMatches;
class BinFolderOpAround;
class BinFolderValue;
class BinFolderList;
class BinFolderAddFilter;
class BinFolderDelFilter;
class NewFolderGUI;
class NewFolderThread;
class ModifyFolderGUI;
class ModifyFolderThread;
class ModifyTargetGUI;
class ModifyTargetThread;
class ModifyTargetPatternsGUI;
class ModifyTargetFileSizeGUI;
class ModifyTargetTimeGUI;
class ModifyTargetTrackTypeGUI;
class ModifyTargetWidthGUI;
class ModifyTargetHeightGUI;
class ModifyTargetFramerateGUI;
class ModifyTargetSamplerateGUI;
class ModifyTargetChannelsGUI;
class ModifyTargetDurationGUI;

#endif
