
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef CANVAS_INC
#define CANVAS_INC

class Canvas;
class CanvasOutput;
class CanvasFullScreen;
class CanvasXScroll;
class CanvasYScroll;
class CanvasFullScreenPopup;
class CanvasSubWindowItem;
class CanvasPopup;
class CanvasZoomSize;
class CanvasSizeSubMenu;
class CanvasPopupSize;
class CanvasPopupAuto;
class CanvasPopupResetCamera;
class CanvasPopupResetProjector;
class CanvasPopupCameraKeyframe;
class CanvasPopupProjectorKeyframe;
class CanvasToggleControls;
class CanvasFullScreenItem;
class CanvasPopupResetTranslation;
class CanvasPopupRemoveSource;

#endif
