
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef CWINDOWTOOL_INC
#define CWINDOWTOOL_INC

class CWindowTool;
class CWindowToolGUI;
class CWindowCoord;
class CWindowCurveToggle;
class CWindowCropOK;
class CWindowCropGUI;
class CWindowMaskItems;
class CWindowMaskName;
class CWindowMaskFade;
class CWindowMaskFadeSlider;
class CWindowMaskMode;
class CWindowMaskDelMask;
class CWindowMaskAffectedPoint;
class CWindowMaskDelPoint;
class CWindowMaskFeather;
class CWindowMaskFeatherSlider;
class CWindowMaskClrMask;
class CWindowMaskClrFeather;
class CWindowMaskBeforePlugins;
class CWindowDisableOpenGLMasking;
class CWindowMaskGUI;
class CWindowEyedropGUI;
class CWindowEyedropCheckBox;
class CWindowCameraGUI;
class CWindowCameraLeft;
class CWindowCameraCenter;
class CWindowCameraRight;
class CWindowCameraTop;
class CWindowCameraMiddle;
class CWindowCameraBottom;
class CWindowProjectorGUI;
class CWindowProjectorLeft;
class CWindowProjectorCenter;
class CWindowProjectorRight;
class CWindowProjectorTop;
class CWindowProjectorMiddle;
class CWindowProjectorBottom;
class CWindowRulerGUI;

#endif
