#ifndef _DBWINDOW_INC_
#define _DBWINDOW_INC_

class DbSearchItem;
class DbWindow;
class DbWindowGUI;
class DbWindowInfoText;
class DbWindowTitleText;
class DbWindowMatchCase;
class DbWindowText;
class DbWindowStart;
class DbWindowDeleteItems;
class DbWindowCancel;
class DbWindowList;
class DbWindowCanvas;
class DbWindowVIcon;
class DbWindowVIconThread;
class DbWindowItem;
class DbWindowScan;

#endif
