
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef __DVDCREATE_INC__
#define __DVDCREATE_INC__

class CreateDVD_MenuItem;
class CreateDVD_Thread;
class CreateDVD_OK;
class CreateDVD_Cancel;
class CreateDVD_DiskSpace;
class CreateDVD_TmpPath;
class CreateDVD_AssetTitle;
class CreateDVD_Deinterlace;
class CreateDVD_InverseTelecine;
class CreateDVD_Scale;
class CreateDVD_ResizeTracks;
class CreateDVD_Histogram;
class CreateDVD_LabelChapters;
class CreateDVD_UseRenderFarm;
class CreateDVD_WideAudio;
class CreateDVD_WideAspect;
class CreateDVD_UseFFMpeg;
class CreateDVD_GUI;
class CreateDVD_FormatItem;
class CreateDVD_Format;
class CreateDVD_MediaSize;

#endif
