
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef EDITPANEL_INC
#define EDITPANEL_INC

#define MWINDOW_ID 0
#define CWINDOW_ID 1
#define VWINDOW_ID 2

class EditInPoint;
class EditOutPoint;
class EditDelInPoint;
class EditDelOutPoint;
class EditSplice;
class EditOverwrite;
class EditLift;
class EditExtract;
class EditToClip;
class EditManualGoto;
class EditCut;
class EditCommercial;
class EditClick2Play;
class EditCopy;
class EditAppend;
class EditInsert;
class EditPaste;
class EditTransition;
class EditPresentation;
class EditUndo;
class EditRedo;
class EditLabelbutton;
class EditFit;
class EditFitAutos;
class EditPrevLabel;
class EditNextLabel;
class EditPrevEdit;
class EditNextEdit;
class ArrowButton;
class IBeamButton;
class KeyFrameButton;
class LockLabelsButton;
class EditPanel;

#endif
