
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef MAINMENU_INC
#define MAINMENU_INC

#define MENUBARPIXELS 25

class MainMenu;
class Undo;
class MainDumpsSubMenu;
class MainDumpsMenu;
class DumpCICache;
class DumpEDL;
class DumpPlugins;
class DumpAssets;
class DumpUndo;
class Redo;
class Cut;
class Copy;
class Paste;
class Clear;
class CutKeyframes;
class CopyKeyframes;
class PasteKeyframes;
class ClearKeyframes;
class StraightenKeyframes;
class BendKeyframes;
class KeyframeCurveType;
class KeyframeCurveTypeMenu;
class KeyframeCurveTypeItem;
class CutDefaultKeyframe;
class CopyDefaultKeyframe;
class PasteDefaultKeyframe;
class ClearDefaultKeyframe;
class PasteSilence;
class SelectAll;
class ClearLabels;
class CutCommercials;
class DetachTransitions;
class MuteSelection;
class TrimSelection;
class MixerItems;
class MixerViewer;
class TileMixers;
class AddAudioTrack;
class DeleteAudioTrack;
class DefaultATransition;
class MapAudio1;
class MapAudio2;
class AddVideoTrack;
class DeleteVideoTrack;
class ResetTranslation;
class DefaultVTransition;
class AddSubttlTrack;
class PasteSubttl;
class MoveTracksUp;
class MoveTracksDown;
class DeleteTracks;
class ConcatenateTracks;
class DeleteFirstTrack;
class DeleteLastTrack;
class LoopPlayback;
class SetBRenderActive;
class LabelsFollowEdits;
class PluginsFollowEdits;
class KeyframesFollowEdits;
class CursorOnFrames;
class TypelessKeyframes;
class ScrubSpeed;
class SaveSettingsNow;
class ShowVWindow;
class ShowAWindow;
class ShowGWindow;
class ShowCWindow;
class ShowLWindow;
class TileWindows;
class SplitX;
class SplitY;
class LoadLayoutItem;
class LoadLayout;
class LoadLayoutDialog;
class LoadLayoutNameText;
class LoadLayoutConfirm;

#endif
