
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef MAINWINDOWGUI_INC
#define MAINWINDOWGUI_INC


#define BUTTONBARHEIGHT 30
#define BUTTONBARWIDTH 50
#define TOTAL_PANES 4
// pane numbers
#define TOP_LEFT_PANE 0
#define TOP_RIGHT_PANE 1
#define BOTTOM_LEFT_PANE 2
#define BOTTOM_RIGHT_PANE 3

// keyframe reticle
#define HAIRLINE_NEVER 0
#define HAIRLINE_DRAGGING 1
#define HAIRLINE_ALWAYS 2

class MWindowGUI;

#endif
