
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef RECORDPREFS_INC
#define RECORDPREFS_INC

#define RECORD_POS_TIMESTAMPS 0
#define RECORD_POS_SOFTWARE 1
#define RECORD_POS_DEVICE 2
#define RECORD_POS_SAMPLE 3

class RecordPrefs;
class RecordFragment;
class RecordWriteLength;
//class DuplexEnable;
class RecordRealTime;
class RecordSampleRate;
class RecordRealtimeTOC;
class RecordPositioning;
class RecordSyncDrives;
class RecordMap51_2;
class VideoWriteLength;
class VideoCaptureLength;
class CaptureLengthTumbler;
class RecordW;
class RecordH;
class RecordFrameRate;
class RecordFrameRateText;
class RecordChannels;
class RecordGain;

#endif
