include ../../plugin_defs

PLUGIN = theme_blond_cv
OBJS = $(OBJDIR)/blondcvtheme.o
OUTPUT_THEME = $(OUTPUT)

CFLAGS += -I../../$(AVC_DIR) -I../../$(LIBRAW_DIR)

include ../../plugin_config

$(OBJDIR)/blondcvtheme.o: blondcvtheme.C

