include ../../plugin_defs

OBJS := \
	$(OBJDIR)/motion51.o \
	$(OBJDIR)/motionwindow51.o

PLUGIN = motion51

include ../../plugin_config

$(OBJDIR)/motion51.o: motion51.C
$(OBJDIR)/motionwindow51.o: motionwindow51.C

