#ifndef __MOTION_51_INC__
#define __MOTION_51_INC__

class Motion51Config;
class Motion51Main;
class Motion51ScanPackage;
class Motion51ScanUnit;
class Motion51Scan;

class Motion51SampleSteps;
class Motion51DrawVectors;
class Motion51TrackingFile;
class Motion51Limits;
class Motion51ResetConfig;
class Motion51ResetTracking;
class Motion51EnableTracking;
class Motion51Window;

#define TRACKING_FILE "/tmp/motion51"

#endif
