include ../../plugin_defs

OBJS := \
	$(OBJDIR)/sketcher.o \
	$(OBJDIR)/sketcherwindow.o

PLUGIN = sketcher

include ../../plugin_config

$(OBJDIR)/sketcher.o: sketcher.C
$(OBJDIR)/sketcherwindow.o: sketcherwindow.C

