include ../../plugin_defs

OBJS := \
	$(OBJDIR)/tracer.o \
	$(OBJDIR)/tracerwindow.o

PLUGIN = tracer

include ../../plugin_config

$(OBJDIR)/tracer.o: tracer.C
$(OBJDIR)/tracerwindow.o: tracerwindow.C

