include ../../plugin_defs

OBJS = $(OBJDIR)/seltempavg.o  \
	$(OBJDIR)/seltempavgwindow.o

PLUGIN = seltempavg

include ../../plugin_config


$(OBJDIR)/seltempavg.o: seltempavg.C
$(OBJDIR)/seltempavgwindow.o: seltempavgwindow.C
